---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by felvmel.
--- DateTime: 04.12.2024 18:19
---

local open = io.open

local left_map = {}
local right_map = {}

local function read_file(path)
  ---@type table
  local file = open(path, "rb") -- r read mode and b binary mode
  if not file then
    return nil
  end

  for line in io.lines(path) do
    local words = {}
    for word in line:gmatch("%w+") do
      table.insert(words, word)
    end

    table.insert(left_map, words[1])
    table.insert(right_map, words[2])
  end

  file:close()
end

read_file("01/input.txt");
table.sort(left_map)
table.sort(right_map)

local distance = 0
if #left_map == #right_map then
  for i = 1, #left_map do
    local sub = left_map[i] - right_map[i]
    if sub < 0 then
      sub = -sub
    end

    distance = distance + sub
  end
else
  distance = nil
end
print(distance)